# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: pgvector/pgvector:pg16
    restart: no
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
     - "5432:5432"
    network_mode: host
    environment:
       POSTGRES_USER: guest
       POSTGRES_PASSWORD: password
       POSTGRES_HOST: localhost
       POSTGRES_PORT: 5432
       POSTGRES_DB: r2r
    volumes:
      - ./postgres-docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080

  neo4j:
    image: neo4j
    restart: no
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    network_mode: host
    environment:
       NEO4J_AUTH: neo4j/password
